apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloudvision-pro
  labels:
    app: cloudvision-pro
spec:
  replicas: 2
  selector:
    matchLabels:
      app: cloudvision-pro
  template:
    metadata:
      labels:
        app: cloudvision-pro
    spec:
      containers:
      - name: cloudvision-container
        image: 919994927167.dkr.ecr.us-east-1.amazonaws.com/my-ecr-repo:latest
        ports:
        - containerPort: 8080
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"
        livenessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5
      imagePullSecrets:
      - name: ecr-secret
---
apiVersion: v1
kind: Service
metadata:
  name: cloudvision-service
  labels:
    app: cloudvision-pro
spec:
  type: LoadBalancer
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
  selector:
    app: cloudvision-pro
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: cloudvision-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: cloudvision-pro
  minReplicas: 2
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80